### ISSUE TITLE
README.md: camel icon largely invisible under dark mode

### ISSUE THREAD

**Issue by shawnlaffan** [perl-ide/.github#3]
The camel icon on the readme is visible mostly as a thin outline of grey cells when github is set to use dark mode.

**Comment by rwp0** [comment]
Right:
![image](https://github.com/perl-ide/.github/assets/68062695/4149610a-ba18-4dfb-8391-8332f3febf02)

**Comment by bmeneg** [comment]
Hmm.. I'll have to keep the white background, otherwise the camel will never appear since it's black.

**Comment by bmeneg** [comment]
Please, take a look in the version I'm using in the PR I just opened to fix it:

![image](https://github.com/perl-ide/.github/assets/453611/2f25e7f1-d47a-49f4-84c9-41ea8ac44d65)

**Comment by shawnlaffan** [comment]
Thanks.  Works on my system.
